version: "3"
services:
  api-gateway:
    build:
      context: "."
      dockerfile: "./api-gateway/Dockerfile"
    depends_on:
      - chat-service
      - users-service
    environment:
      - PORT=7000
      - USERS_SERVICE_URI=http://users-service:8101
      - CABINETS_SERVICE_URI=http://cabinets-service:8102
    ports:
      - "8000:7000"
    volumes:
      - ./api-gateway:/opt/app

  chat-service:
    build:
      context: "."
      dockerfile: "./chat-service/Dockerfile"
    depends_on:
      - chat-service-db
    environment:
      - PORT=8100
    ports:
      - "8100:8100"
    volumes:
      - ./chat-service:/opt/app

  chat-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - "8200:3306"

  cabinets-service:
    build:
      context: "."
      dockerfile: "./cabinets-service/Dockerfile"
    depends_on:
      - cabinets-service-db
    environment:
      - PORT=8102
      - CABINETS_SERVICE_DB_URL=mysql://root:password@cabinets-service-db/db
    ports:
      - "8102:8102"
    volumes:
      - ./cabinets-service:/opt/app

  cabinets-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - "8202:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - chat-service-db
      - users-service-db
    ports:
      - "8300:80"
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

  users-service:
    build:
      context: "."
      dockerfile: "./users-service/Dockerfile"
    environment:
      - PORT=8101
      - USERS_SERVICE_DB_URL=mysql://root:password@users-service-db/db
      - USER_SESSION_EXPIRY_HOURS=1
    depends_on:
      - users-service-db
    ports:
      - "8101:8101"
    volumes:
      - ./users-service:/opt/app

  users-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    image: mysql:5.7.20
    ports:
      - "8201:3306"
